import Head from 'next/head'

export default function Seo({ title }: { title: string }) {
    return (
        <Head>
            <title>{`나의 NEXTJS | ${title}`}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favi.ico" />
        </Head>
    );
}